Newer and smarter build system
- Localversion is set now by pdesire_build
- moved mkbootimg to scripts folder
- Add trap if C^ is pressed to abort properly
- Switch to Linaro GCC 7.1.1

Signed-off-by: Tristan Marsell <tristan.marsell@t-online.de>

diff --git a/pdesire_build b/pdesire_build
--- a/pdesire_build
+++ b/pdesire_build
@@ -3,6 +3,14 @@
 echo "XperiaSatsukiEliteKernel Buildscript"
 echo
 
+exitfn () {
+    trap SIGINT              # Restore signal handling for SIGINT
+    echo " "
+    echo "Aborted."
+    sed -i 's/-'"$kernel_version"'/placeholder/g' arch/arm64/configs/diffconfig/common_diffconfig
+    exit                     #   then exit script.
+}
+
 function goto
 {
     label=$1
@@ -20,12 +28,11 @@ if [ -z "$MY_PATH" ] ; then
 fi
 
 # Tuneables Here
-toolchain="aarch64-linux-gnu-6.3.1"
+toolchain="aarch64-linux-gnu-7.1.1"
 prefix="aarch64-linux-gnu-"
 toolchain_path="/home/PDesire/kernel/toolchains/$toolchain/bin/:$PATH"
-clang_path="/home/PDesire/kernel/toolchains/$clang/bin"
 name_of_your_kernel="XperiaSatsukiEliteKernel"
-kernel_version="Two"
+kernel_version="Three-EAS-DevElite"
 defconfig="msm8994-perf_defconfig"
 cpu_jobs="`grep -c ^processor /proc/cpuinfo`"
 kerneltype="Image.gz-dtb"
@@ -42,8 +49,12 @@ export ARCH=arm64
 export PATH=$toolchain_path
 export CROSS_COMPILE=$prefix
 
+trap "exitfn" INT            # Set up SIGINT trap to call function.
+
 # Go to kernel root
 cd $MY_PATH
+
+sed -i 's/placeholder/-'"$kernel_version"'/g' arch/arm64/configs/diffconfig/common_diffconfig
 
 while read -p "Do you want to make clean (y/n)? " cchoice
 do
@@ -147,7 +158,7 @@ echo
 
 if [ -f arch/arm64/boot/"$kerneltype" -a ! -f final_files/*.img ]; then
 	echo "Making boot.img..."
-	./mkbootimg --cmdline "$cmdline" --base $base --kernel arch/arm64/boot/Image.gz-dtb --ramdisk elitekernelfiles/$device_codename/ramdisk.cpio.gz --ramdisk_offset $ramdisk_offset --pagesize $ps -o final_files/boot_$device_name.img --tags_offset $tags_offset
+	./scripts/mkbootimg --cmdline "$cmdline" --base $base --kernel arch/arm64/boot/Image.gz-dtb --ramdisk elitekernelfiles/$device_codename/ramdisk.cpio.gz --ramdisk_offset $ramdisk_offset --pagesize $ps -o final_files/boot_$device_name.img --tags_offset $tags_offset
 
 else 
 	echo "$kerneltype not found, take a look on logs folder to see what causes the problem. Aborted."
@@ -169,5 +180,8 @@ else
 	echo "boot.img not found. Aborted."
 fi
 
+sed -i 's/-'"$kernel_version"'/placeholder/g' arch/arm64/configs/diffconfig/common_diffconfig
+
 end:
+trap SIGINT                  # Restore signal handling to previous before exit.
 exit 0;
